<?xml version="1.0" encoding="utf-8"?><Database Name="EddyScoresDB" Class="ScoresDALDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=EddyScoresDB;Integrated Security=True" SettingsObjectName="ScoreDataSaverLib.Properties.Settings" SettingsPropertyName="EddyScoresDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblMatches" Member="Matches">
    <Type Name="Match">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="League" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HomeTeam" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AwayTeam" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MatchDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="HomeScore" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AwayScore" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Field" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>