//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoreCollector.Test.SaverReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SaverReference.ISaverServiceContract")]
    public interface ISaverServiceContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaverServiceContract/SaveScore", ReplyAction="http://tempuri.org/ISaverServiceContract/SaveScoreResponse")]
        bool SaveScore(ScoreFramwork.Score[] scoreList);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISaverServiceContractChannel : ScoreCollector.Test.SaverReference.ISaverServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaverServiceContractClient : System.ServiceModel.ClientBase<ScoreCollector.Test.SaverReference.ISaverServiceContract>, ScoreCollector.Test.SaverReference.ISaverServiceContract {
        
        public SaverServiceContractClient() {
        }
        
        public SaverServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SaverServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SaverServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SaverServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SaveScore(ScoreFramwork.Score[] scoreList) {
            return base.Channel.SaveScore(scoreList);
        }
    }
}
